#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-python_slugify
Version  : 6.0.1
Release  : 37
URL      : https://files.pythonhosted.org/packages/b9/1b/f2d89e911b8234e6902b2065b1db5a375ee0867e4c65997a6c9fc584d77f/python-slugify-6.0.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/b9/1b/f2d89e911b8234e6902b2065b1db5a375ee0867e4c65997a6c9fc584d77f/python-slugify-6.0.1.tar.gz
Summary  : A Python slugify application that also handles Unicode
Group    : Development/Tools
License  : MIT
Requires: pypi-python_slugify-license = %{version}-%{release}
Requires: pypi-python_slugify-python = %{version}-%{release}
Requires: pypi-python_slugify-python3 = %{version}-%{release}
Requires: pypi(unidecode)
BuildRequires : buildreq-distutils3
BuildRequires : pypi(text_unidecode)

%description
**A Python slugify application that handles unicode**.
        
        [![status-image]][status-link]
        [![version-image]][version-link]
        [![coverage-image]][coverage-link]
        
        # Overview
        
        **Best attempt** to create slugs from unicode strings while keeping it **DRY**.
        
        # Notice

%package license
Summary: license components for the pypi-python_slugify package.
Group: Default

%description license
license components for the pypi-python_slugify package.


%package python
Summary: python components for the pypi-python_slugify package.
Group: Default
Requires: pypi-python_slugify-python3 = %{version}-%{release}

%description python
python components for the pypi-python_slugify package.


%package python3
Summary: python3 components for the pypi-python_slugify package.
Group: Default
Requires: python3-core
Provides: pypi(python_slugify)
Requires: pypi(text_unidecode)

%description python3
python3 components for the pypi-python_slugify package.


%prep
%setup -q -n python-slugify-6.0.1
cd %{_builddir}/python-slugify-6.0.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1645061722
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-python_slugify
cp %{_builddir}/python-slugify-6.0.1/LICENSE %{buildroot}/usr/share/package-licenses/pypi-python_slugify/39348c15454a917e7a44ef76017b198dc3834d8d
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-python_slugify/39348c15454a917e7a44ef76017b198dc3834d8d

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
